### ISSUE TITLE
A typing fix and a question

### ISSUE THREAD

**Issue by Ali-Shaha** [kahilah/ct2foam#2]
In ct2foam_utils.py, [line 178](https://github.com/kahilah/ct2foam/blob/dc6ac961991a11b9978729c4fd052ca2893e5a61/ct2foam/thermo_transport/ct2foam_utils.py#L178) , "_transport" could possibly change to "_thermo".

Also is there any particular reason that T range is set to [280,3000]? since this range could be different for each specie or could be extended up to 6000K in thermo file.

**Comment by kahilah** [comment]
Thanks for reporting the issue. Fixed in the latest commit. 

Regarding your other question, note that [280, 3000] is the default interval in the `ctThermoTransport `class (see `ct_properties.py`), which is further used in the fitting process.

However, that does not mean that you couldn't change it. So in that case you just build your own execution script in which you define:
`data = ct_properties.ctThermoTransport(args.input, T=np.linspace(280,6000,256), Tmid=args.Tmid)`

It is true that this range can be different for each specie, but when utilising thermophysical data in a CFD code, it is typically preferrable to have shared bounds to 
1) enhance solver performance of the thermodynamics evaluation as codes can assume shared min/max/Tmid limits, 
2) to ease user debugging as it's easier to understand if your domain temperature goes over a general thermo limit instead of an individual one among hundreads of specie.

**Comment by kahilah** [comment]
And to finalise the note, I'm hesitated to increase the default limits above 3000K as most chemical mechanisms include species with data limited to such scale.
